### ISSUE TITLE
Allow viewing comments without opening linked page

### ISSUE THREAD

**Issue by cheapsteak** [pumpkinz/pumpkin-reader#130]

**Comment by timotiusnc** [comment]
Hi cheapsteak,

You can set it on Settings.
**Uncheck** option **Show Link First**.

Hope this helps.

![unnamed](https://cloud.githubusercontent.com/assets/843403/15698638/c43d5a9e-27f0-11e6-932e-d5f382f9710e.png)

**Comment by cheapsteak** [comment]
Ah, thank you!
