### ISSUE TITLE
Intermittent Comment List Bug

### ISSUE THREAD

**Issue by wiseodd** [pumpkinz/pumpkin-reader#47]
There seems to be an intermittent bug about comment list, esp. when collapsing and extending the comments.

**Comment by timotiusnc** [comment]
What's the bug?

**Comment by wiseodd** [comment]
Sorry for late reply.
I caught a cold.

Just try messing around with expanding and collapsing comments.
You'll soon notice. It's hard to reproduce though.

**Comment by wiseodd** [comment]
Fixed by #48
