### ISSUE TITLE
Unable to go back after following link

### ISSUE THREAD

**Issue by eckyputrady** [pumpkinz/pumpkin-reader#54]
1. Open any HN story with in-app web view
2. Follow any link
3. Press "back"
4. Expectation: go back to original story. Actual: Goes back to Story list.

New update looks good btw

**Comment by wiseodd** [comment]
Thanks for contributing!

We'll look at this ASAP.
In the meantime, if this is really important for you, you can use external browser. It will use Chrome, so the behavior should look like as you expected.
