### ISSUE TITLE
Tell which story that has been read?

### ISSUE THREAD

**Issue by eckyputrady** [pumpkinz/pumpkin-reader#55]
As a reader who regularly check HN, I'd like to know quickly which stories I've read so I don't open them twice and to filter which story to read is easier.

One of the perk of being webapp for http://cheeaun.github.io/hackerweb/ is that visited link is shown in different color. It is really helpful to quickly scan which story is already read.

**Comment by wiseodd** [comment]
Thanks!

That would be useful indeed! 
Working on this ASAP.

**Comment by timotiusnc** [comment]
Wow, never thought about that.
Thanks for the input!
