### ISSUE TITLE
Data Storage Getting Bigger and Bigger

### ISSUE THREAD

**Issue by timotiusnc** [pumpkinz/pumpkin-reader#60]
The `Data` part of Pumpkin Reader app goes up to ~20MB.

Investigate why the app takes quite a lot of storage.
Possible cause: Rx `cache()` method.

**Comment by timotiusnc** [comment]
The culprit: internal WebView cache.
Everytime user opens an unread news with interval WebView, the data will spike up. Turned out WebView cache is stored in `data` part. If user uses external WebView, there is no spike in storage.
This happened on Cyanogen OS.

Interestingly, on Oxygen OS, the cache is stored in `cache` part.

So the spike of storage size is expected, user can always clear it out themselves or we can add the functionality in the future.

**Comment by wiseodd** [comment]
Let user manually clear the cache if they want to
