### ISSUE TITLE
Links target URL get truncated in comments

### ISSUE THREAD

**Issue by guillaumekln** [pumpkinz/pumpkin-reader#89]
Hi,

When users include links in their comment, they sometimes point to the truncated URL that appears in the text instead of the actual and full URL. It doesn't happen directly after loading the comments but only after browsing them a bit.

I was unable to find a clear pattern, but here is a scenario:
1. Load in Pumpkin Reader [this recent news](https://news.ycombinator.com/item?id=10481507) which contains some visually truncated links
2. Scroll down as you do when browsing comments
3. Click on a visually truncated comment
4. The browser tries to open the truncated URL instead of the actual URL

You can even see a visual difference when it happens:
- After loading the comments, the first comment's link looks like [this](https://drive.google.com/open?id=0B-gWAI-JybKRUVAyOWFmWkJCOGs).
- After browsing the comments and coming back to the first comment, it looks like [this](https://drive.google.com/open?id=0B-gWAI-JybKRV2pGQVBWVFg5LUk).

Thanks for this excellent HN client!

**Comment by timotiusnc** [comment]
Hi @guillaumekln 

Thank you for the bug report!

We have tried it and yes, it is reproducible. Your scenario and screenshots helped a lot!
We are currently working on this issue. Hopefully we can ship the bug fix on next release.

It is our great pleasure that you find Pumpkin Reader an excellent HN client.
Thank you again!

**Comment by timotiusnc** [comment]
The above commit is wrong. It's supposed to refer to #91.
