### ISSUE TITLE
Wrong comment dates after screen rotation

### ISSUE THREAD

**Issue by guillaumekln** [pumpkinz/pumpkin-reader#91]
When on the comment section, rotating the screen causes all dates to have bad values.
- [Before rotation](https://drive.google.com/open?id=0B-gWAI-JybKRUnhuc0pzME9GUGc)
- [After rotation](https://drive.google.com/open?id=0B-gWAI-JybKRbXY0a2JoaFFubm8)

**Comment by timotiusnc** [comment]
Ooh, @guillaumekln you're right again.

Thanks (again) for the bug report!

We're fixing it.
