### ISSUE TITLE
Implement intent filter for hacker news links

### ISSUE THREAD

**Issue by wiseodd** [pumpkinz/pumpkin-reader#96]
So that when the user click a HN link, it will be opened directly in Pumpkin Reader

http://developer.android.com/guide/components/intents-filters.html

**Comment by timotiusnc** [comment]
Hahaha, I've been meaning to add this to the backlog.
Roy has asked me personally about this feature.
He usually reads from Feedly. When he needs to read the comments, he has to open it in browser. Would be great if it were to open on Pumpkin Reader.
